import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';

const prod = (process.argv[2] === "production");

const copyAssetsPlugin = {
	name: 'copy-assets',
	setup(build) {
		build.onEnd(() => {
			// Ensure test-vault plugin directory exists
			const testVaultDir = 'test-vault/.obsidian/plugins/self-test';
			if (!existsSync(testVaultDir)) {
				mkdirSync(testVaultDir, { recursive: true });
			}
			copyFileSync('styles.css', `${testVaultDir}/styles.css`);
			copyFileSync('manifest.json', `${testVaultDir}/manifest.json`);
			if (prod) {
				// Copy built main.js from test-vault to repo root for GitHub releases
				copyFileSync(`${testVaultDir}/main.js`, 'main.js');
			} else {
				// In dev mode, copy to test-vault only (outfile writes there directly)
			}
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [copyAssetsPlugin],
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "test-vault/.obsidian/plugins/self-test/main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
